# Overrides to relax some rules for the test source-sets.
comments:
  AbsentOrWrongFileLicense:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  StringLiteralDuplication:
    active: false

potential-bugs:
  UnnamedParameterUse:
    active: false

style:
  MagicNumber:
    active: false
