name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release. (e.g.: `0.1.0-SNAPSHOT`)"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ inputs.version }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JVM
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: 'publish'
