name: 'Publish'

on:
  workflow_dispatch:
    inputs:
      isRelease:
        description: "Production Release"
        type: boolean
        required: false
        default: false

jobs:
  Publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_BUILD: ${{ inputs.isRelease }}
      PUBLISHING_ENABLED: true
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Java'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
      - name: 'Publish'
        run: ./gradlew --no-build-cache clean build publishToMavenCentral
