name: 'Publish'

# Action Dependency Pins:
# actions/checkout            - de0fac2e4500dabe0009e67214ff5f5447ce83dd - v6.0.2 - https://github.com/actions/checkout/releases
# actions/setup-java          - be666c2fcd27ec809703dec50e508c2fdc7f6654 - v5.2.0 - https://github.com/actions/setup-java/releases
# gradle/actions/setup-gradle - 0723195856401067f7a2779048b490ace7a47d7c - v5.0.2 - https://github.com/gradle/actions/releases

on:
  workflow_dispatch:
    inputs:
      isRelease:
        description: "Production Release"
        type: boolean
        required: false
        default: false

jobs:
  Publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_BUILD: ${{ inputs.isRelease }}
      PUBLISHING_ENABLED: true
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: 'Setup Java'
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c
        with:
          cache-read-only: true
      - name: 'Publish'
        run: ./gradlew --no-build-cache clean build publishToMavenCentral
