name: 'Publish'

# Action Dependency Pins:
# actions/checkout            - 08c6903cd8c0fde910a37f88322edcfb5dd907a8 - v5.0.0 - https://github.com/actions/checkout/releases
# actions/setup-java          - dded0888837ed1f317902acf8a20df0ad188d165 - v5.0.0 - https://github.com/actions/setup-java/releases
# gradle/actions/setup-gradle - 4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 - v5.0.0 - https://github.com/gradle/actions/releases

on:
  workflow_dispatch:
    inputs:
      isRelease:
        description: "Production Release"
        type: boolean
        required: false
        default: false

jobs:
  Publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_BUILD: ${{ inputs.isRelease }}
      PUBLISHING_ENABLED: true
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: 'Setup Java'
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
        with:
          cache-read-only: true
      - name: 'Publish'
        run: ./gradlew --no-build-cache clean build publishToMavenCentral
